### ISSUE TITLE
Refactor Recipe

### ISSUE THREAD

**Issue by AnnaPete** [dgubko/whats-cookin#16]
Right now, it's an array of recipe objects. It needs to be a single recipe object.

+ name method
+ ingredients cost per unit method
+ instructions method
+ total cost method

**Comment by LaurenBlack5280** [comment]
# There is a previous branch where there are properties and methods passing tests:
- [x] A Recipe represents one recipe object.
- [x] It should hold on to all its information (all properties are contained in the object).
## It should have methods to:
- [ ] Determine the names of ingredients needed- The method currently returns a list of id numbers. I need help with class to class interaction with the Ingredients class to access the name property.
- [ ] Get the cost of its ingredients- once I am on track again with class to class interaction, I will be able to tackle this problem also. There is a lot of data to parse through. I can access the id numbers, but need help accessing the quantity and amount properties only available in the ingredients class.
- [x] Return its directions / instructions

**Comment by dgubko** [comment]
I started working on it and have some progress.

**Comment by dgubko** [comment]
Refactoring complete, tests written and passing, asking for review
