### ISSUE TITLE
README file

### ISSUE THREAD

**Issue by AnnaPete** [dgubko/whats-cookin#40]
We need to create a readme file:

- [x]  Overview of project and goals
- [x]   Technologies used 
- [x]   Challenges, wins, and any other reflections
- [x]  Screenshots/gifs of your app
- [x]   List of contributors

**Comment by LaurenBlack5280** [comment]
I can finalize the gif once we make any final changes. 
I would like to add an additional section:

- [x] Project Install

**Comment by AnnaPete** [comment]
Done!
